### ISSUE TITLE
Installation doesn’t work on Raspberry Pi

### ISSUE THREAD

**Issue by wazdra** [YunoHost-Apps/radarr_ynh#1]
### Describe the bug

Installation fails from the webadmin (I have not tried from CLI)

### Context

- Hardware: Raspberry Pi 4
- YunoHost version: 4.2.4
- I have access to my server: Through SSH | through the webadmin
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: no
- Using, or trying to install package version/branch: 3.1.1.4954~ynh1

### Steps to reproduce

- Install the app from the webadmin with default settings

### Expected behavior

The app should get installed.

### Logs

https://paste.yunohost.org/ahugazezer

**Comment by tituspijean** [comment]
Hello, thanks for your report!

Can you try the linked testing PR? It worked on my RPi4 with `armhf` architecture, like yours.
You can install it with `yunohost app install https://github.com/YunoHost-Apps/radarr_ynh/tree/testing --force`

🤞
