### ISSUE TITLE
Authentication Required 

### ISSUE THREAD

**Issue by seedrick** [YunoHost-Apps/radarr_ynh#32]
![Screenshot_20231030-181900.png](https://github.com/YunoHost-Apps/radarr_ynh/assets/15255246/cd23ea65-f5f2-49a7-a2fb-32c920f40588)

I'm met with this screen since the last update. What went wrong?

**Comment by tituspijean** [comment]
Sorry for the inconvenience. Can you check the value of `AuthenticationMethod` in `/home/yunohost.app/radarr/config.xml`?

**Comment by tituspijean** [comment]
Should be fixed with the current testing branch. It adds a config panel with a button to disable Radarr's own authentication system.

**Comment by tituspijean** [comment]
Fix has been released.
